### ISSUE TITLE
serwer_ksiadz_papiez_wodaswiecona_niebiesko_microsoft_github_ziemniak_premium_picture_shutterstock.webp

### ISSUE THREAD

**Issue by Igreky** [VenomPCPL/VenomPCPL#3]
microsoft woda święcona simulator 2077
![micorosft_ksiadz_simulator_2077](https://user-images.githubusercontent.com/39243548/99964160-2ccce500-2d93-11eb-9dd7-cde8df0daac5.png)

**Comment by MinecraftCiach** [comment]
ej igrek

**Comment by Minecrafterr** [comment]
ej ciach

**Comment by rkubapl** [comment]
kolęda

**Comment by MinecraftCiach** [comment]
> ej ciach
co

**Comment by Minecrafterr** [comment]
> > ej ciach
> 
> co

jajco hahahha

**Comment by MinecraftCiach** [comment]
> > > ej ciach
> > 
> > 
> > co
> 
> jajco hahahha

c o

**Comment by Minecrafterr** [comment]
> > > > ej ciach
> > > 
> > > 
> > > co
> > 
> > 
> > jajco hahahha
> 
> c o

bajo jajo

**Comment by MinecraftCiach** [comment]
> > > > > ej ciach
> > > > 
> > > > 
> > > > co
> > > 
> > > 
> > > jajco hahahha
> > 
> > 
> > c o
> 
> bajo jajo

Ty pojebie kurwa się zamknij tam kurwa nie bajo jajo ty pierdolony chamie.

**Comment by rkubapl** [comment]
ok

**Comment by Minecrafterr** [comment]
> > > > > > ej ciach
> > > > > 
> > > > > 
> > > > > co
> > > > 
> > > > 
> > > > jajco hahahha
> > > 
> > > 
> > > c o
> > 
> > 
> > bajo jajo
> 
> Ty pojebie kurwa się zamknij tam kurwa nie bajo jajo ty pierdolony chamie.

ale kresek
![image](https://user-images.githubusercontent.com/61909942/103457705-d774e380-4d01-11eb-8e7b-2713e65ccb38.png)

**Comment by MinecraftCiach** [comment]
> > > > > > > ej ciach
> > > > > > 
> > > > > > 
> > > > > > co
> > > > > 
> > > > > 
> > > > > jajco hahahha
> > > > 
> > > > 
> > > > c o
> > > 
> > > 
> > > bajo jajo
> > 
> > 
> > Ty pojebie kurwa się zamknij tam kurwa nie bajo jajo ty pierdolony chamie.
> 
> ale kresek
> ![image](https://user-images.githubusercontent.com/61909942/103457705-d774e380-4d01-11eb-8e7b-2713e65ccb38.png)

no

**Comment by Minecrafterr** [comment]
> > > > > > > > ej ciach
> > > > > > > 
> > > > > > > 
> > > > > > > co
> > > > > > 
> > > > > > 
> > > > > > jajco hahahha
> > > > > 
> > > > > 
> > > > > c o
> > > > 
> > > > 
> > > > bajo jajo
> > > 
> > > 
> > > Ty pojebie kurwa się zamknij tam kurwa nie bajo jajo ty pierdolony chamie.
> > 
> > 
> > ale kresek
> > ![image](https://user-images.githubusercontent.com/61909942/103457705-d774e380-4d01-11eb-8e7b-2713e65ccb38.png)
> 
> no

ja lece nara

https://user-images.githubusercontent.com/61909942/103457728-0c813600-4d02-11eb-894c-38766ef2a5e5.mp4

**Comment by MinecraftCiach** [comment]
> > > > > > > > > ej ciach
> > > > > > > > 
> > > > > > > > 
> > > > > > > > co
> > > > > > > 
> > > > > > > 
> > > > > > > jajco hahahha
> > > > > > 
> > > > > > 
> > > > > > c o
> > > > > 
> > > > > 
> > > > > bajo jajo
> > > > 
> > > > 
> > > > Ty pojebie kurwa się zamknij tam kurwa nie bajo jajo ty pierdolony chamie.
> > > 
> > > 
> > > ale kresek
> > > ![image](https://user-images.githubusercontent.com/61909942/103457705-d774e380-4d01-11eb-8e7b-2713e65ccb38.png)
> > 
> > 
> > no
> 
> ja lece nara
> 
>  maseczka.mp4

nie lecisz

**Comment by MinecraftCiach** [comment]
@Minecrafterr wracaj tutaj!

**Comment by 05xapresses** [comment]
https://user-images.githubusercontent.com/40399432/103457809-b52f9580-4d02-11eb-8571-90c0ea2f0c1c.mp4

**Comment by MinecraftCiach** [comment]
Otwieram ponownie

**Comment by MinecraftCiach** [comment]
OTWIERAĆ, FBI

**Comment by Igreky** [comment]
![Screenshot_20210102-140830](https://user-images.githubusercontent.com/39243548/103458025-726ebd00-4d04-11eb-9507-f1199654f69e.png)
